exclude: README.md
repos:
  - repo: https://github.com/ambv/black
    rev: '22.3.0'
    hooks:
      - id: black
        args: ['--quiet']
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: check-case-conflict
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-ast
      - id: check-json
      - id: check-merge-conflict
      - id: detect-private-key
      - id: double-quote-string-fixer
  - repo: https://gitlab.com/pycqa/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        additional_dependencies: [
          'flake8-annotations==2.6.2',  # Enforces type annotation
          'flake8-bugbear==21.4.3',  # Looks for likely bugs and design problems
          'flake8-comprehensions==3.6.1',  # Looks for unnecessary generator functions that can be converted to list comprehensions
          'flake8-deprecated==1.3',  # Looks for method deprecations
          'flake8-docstrings==1.6.0',  # Verifies that all functions/methods have docstrings
          'flake8-print==4.0.0',  # Checks for print statements
          'flake8-type-annotations==0.1.0',  # Looks for misconfigured type annotations
          'flake8-use-fstring==1.1',  # Enforces use of f-strings over .format and %s
        ]
        args: ['--enable-extensions=G']
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v0.941'
    hooks:
      - id: mypy
