version: '3.8'

services:
  postgres:
    container_name: {{ cookiecutter.project_name }}_postgres
    environment:
      POSTGRES_USER: {{ cookiecutter.project_name }}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    image: postgres:13-alpine
    volumes:
      - database:/var/lib/postgresql/data
    ports:
      - '127.0.0.1:5432:5432'
    restart: always

  postgres_test:
    container_name: {{ cookiecutter.project_name }}_postgres_test
    environment:
      POSTGRES_USER: {{ cookiecutter.project_name }}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    image: postgres:13-alpine
    ports:
      - '127.0.0.1:5433:5432'
    restart: always

volumes:
  database:
