# This Dockerfile requires running `npm run build` on the host first
FROM ghcr.io/intility/nginx-unprivileged-react:2.6.3@sha256:55f192839dd4715568edc644edba96adeda7de41363ab5b0a102380d66f8a84d

# Copy build files
COPY dist/ /usr/share/nginx/html
