# This Dockerfile requires running `npm run build` on the host first
FROM ghcr.io/intility/nginx-unprivileged-react:2.6.4@sha256:4842f311d589448f0f66fbef384098bd7cfcc426ae947c02f2d52558b6c9185b

# Copy build files
COPY dist/ /usr/share/nginx/html
