apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "chart.fullname" . }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
{{- with .Values.secrets }}
stringData:
  {{- toYaml . | nindent 2 }}
{{- end }}