name: build, test and publish

on:
  push:
    tags:
      - "*"
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    permissions:
      contents: read
      id-token: write
      packages: write
      attestations: write
      artifact-metadata: write
    uses: intility/reusable-dotnet/.github/workflows/dotnet.yaml@e453a5f751410e99899c5c4123006d148a2a2d19 # v1.4.2
    with:
      directory: ./
      docker: ${{ github.event_name != 'pull_request' }}
      locked-mode: true
