name: build, test and publish

on:
  push:
    tags:
      - "*"
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    permissions:
      contents: read
      id-token: write
      packages: write
      attestations: write
      artifact-metadata: write
    uses: intility/reusable-dotnet/.github/workflows/dotnet.yaml@21456fd1f4a084b1ba9eb316dc543b02d151ddb7 # v1.4.1
    with:
      directory: ./
      docker: ${{ github.event_name != 'pull_request' }}
      locked-mode: true
