name: build, test and publish

on:
  push:
    tags:
      - "*"
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    permissions:
      contents: read
      id-token: write
      packages: write
      attestations: write
      artifact-metadata: write
    uses: intility/reusable-dotnet/.github/workflows/dotnet.yaml@303bdad19616a35638fa80d487afc1359f2fcc5d # v1.2.2
    with:
      directory: ./
      docker: ${{ github.event_name != 'pull_request' }}
