name: build, test and publish

on:
  push:
    tags:
      - "*"
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    permissions:
      contents: read
      id-token: write
      packages: write
      attestations: write
      artifact-metadata: write
    uses: intility/reusable-dotnet/.github/workflows/dotnet.yaml@0df29a647616ad3a6834568d0a2d0aff7911a33c # v1.3.0
    with:
      docker: ${{ github.event_name != 'pull_request' }}
      locked-mode: true
