apiVersion: apps/v1
kind: Deployment
metadata:
  name: __CONTAINER_REPOSITORY__
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 0
  template:
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  app: __CONTAINER_REPOSITORY__
              topologyKey: "kubernetes.io/hostname"
