# Default values for chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
#if (!cronJob)
replicaCount: 1
#endif

image:
  repository: nginx
  pullPolicy: IfNotPresent
  tag: ""

#if (cronJob)
cron:
  schedule: "*/5 * * * *"
  restartPolicy: OnFailure
  concurrencyPolicy: Replace
  failedJobsHistoryLimit: 1
  successfulJobsHistoryLimit: 3
#endif

nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

#if (!cronJob)
resources:
  # It is crucial to specify the resources for this deployment to ensure optimal performance and prevent any potential outages.
  # Failure to set the correct resources can lead to unexpected behavior and degradation of services.
   limits:
     cpu: 100m
     memory: 350Mi
   requests:
     cpu: 30m
     memory: 100Mi
#endif
registry:
  url: https://gitlab-registry.intility.com
  user: ""
  password: ""

config: {}

secrets: {}
