apiVersion: batch/v1
kind: CronJob
metadata:
  name: __CONTAINER_REPOSITORY__
  labels:
    app.openshift.io/runtime: dotnet
spec:
  schedule: "0 0 * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  startingDeadlineSeconds: 200
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          terminationGracePeriodSeconds: 30
          containers:
            - name: __CONTAINER_REPOSITORY__
              image: ghcr.io/intility/__CONTAINER_REPOSITORY__
              imagePullPolicy: Always
              ports:
                - name: http
                  containerPort: 8080
                  protocol: TCP
              envFrom:
                - configMapRef:
                    name: __CONTAINER_REPOSITORY__-config
                - secretRef:
                    name: __CONTAINER_REPOSITORY__-secrets
