# https://github.com/intility/reusable-workflows/blob/main/examples/react/README.md

name: "Build, test and push main branch"

on:
  push:
    branches:
      - main

jobs:
  react:
    permissions:
      contents: read
      packages: write
      id-token: write
      attestations: write
    uses: intility/reusable-react/.github/workflows/react.yaml@v1.1.0
    with:
      # image will be pushed to ghcr.io/intility/<project-name>/react-app
      image-name: __DOCKER_IMAGE_NAME__
      push: true
      sentry: true
      sentry-project: __SENTRY_PROJECT_NAME__
      sentry-release: ${{ github.sha }}
      sentry-environment: production
      # build environment variables
      build-env: |
        VITE_SENTRY_DSN=${{ vars.SENTRY_DSN }}
        VITE_SENTRY_RELEASE=${{ github.sha }}
        VITE_SENTRY_ENVIRONMENT=development
    secrets: inherit
