apiVersion: apps/v1
kind: Deployment
metadata:
  name: __CONTAINER_REPOSITORY__
spec:
  replicas: 3
  template:
    spec:
      containers:
        - name: __CONTAINER_REPOSITORY__
          resources:
            requests:
              memory: 256Mi
            limits:
              memory: 512Mi
