apiVersion: apps/v1
kind: Deployment
metadata:
  name: __CONTAINER_REPOSITORY__
  labels:
    app.openshift.io/runtime: dotnet
spec:
  replicas: 2
  revisionHistoryLimit: 0
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  selector:
    matchLabels:
      app: __CONTAINER_REPOSITORY__
  template:
    metadata:
      labels:
        app: __CONTAINER_REPOSITORY__
    spec:
      containers:
        - name: __CONTAINER_REPOSITORY__
          image: ghcr.io/intility/__CONTAINER_REPOSITORY__
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 20
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 20
          resources:
            limits:
              memory: 512Mi
            requests:
              cpu: 20m
              memory: 128Mi
          envFrom:
            - secretRef:
                name: __CONTAINER_REPOSITORY__-secrets
            - configMapRef:
                name: __CONTAINER_REPOSITORY__-config
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  app: __CONTAINER_REPOSITORY__
              topologyKey: "kubernetes.io/hostname"
